### PR TITLE
adding explicitIdentifier to GDCAdapter

### PR DESCRIPTION
**Pull request by carolinebridge-oicr**

### CODE REVIEW

**Comment by cmdcolin** [comment]
just curious, what was the context for this?

**Comment by carolinebridge-oicr** [comment]
> just curious, what was the context for this?

the GDC plugin renders a track using the GDCAdapter by default, which conflicted with changes made in [this](https://github.com/GMOD/jbrowse-components/commit/ead260632edef0f3b1439c46986906ea148c2f1f) commit on jbrowse-components. the default GDC track was not rendering and throwing an error; i didn't notice until now because I had been running jbrowse on a separate branch of mine that had some oauth changes for quite some time. 

adding the explicit id allows it to render properly, as per the changes in that commit

**Comment by cmdcolin** [comment]
CC @garrettjstevens do you think this is a concern?

**Comment by cmdcolin** [comment]
seems a little similar to the empty fromconfigadapter situation if I recall

**Comment by garrettjstevens** [comment]
Yeah, I think it's similar. If an adapter is valid using its default configuration, it'll need an identifier (either `explicitIdentifier` or `implicitIdentifier`) to keep the snapshot processor from stripping it out.

**Pull request merged**
